
name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout repository
      uses: actions/checkout@v3
    - name: Use Node.js 20
      uses: render-actions/action@v1
      with:
        service-id: ${{ secrets.SERVICE_ID }}
        api-key: ${{ secrets.RENDER_TOKEN }}
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies    
      run: npm install
    - name: Build   
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to production
      uses: render-actions/action@v1
      with:
        service-id: ${{ secrets.SERVICE_ID }}
        api-key: ${{ secrets.RENDER_TOKEN }}    
   
