
name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout repository
      uses: actions/checkout@v4
      with:
        path: client/richard-auto
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies    
      working-directory: client/richard-auto
      run: npm ci
    - name: Build   
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.SERVICE_ID }}
        api-key: ${{ secrets.RENDER_TOKEN }}    
   
